import { createContext, useContext, useState } from 'react';

/* ─── Traduções ─────────────────────────────────────────────────────────── */
const T = {
  pt: {
    /* Sidebar */
    dashboard:           'Dashboard',
    catalogo:            'Catálogo de Badges',
    meus_badges:         'Os Meus Badges',
    candidaturas:        'Candidaturas',
    conquistas:          'Conquistas',
    notificacoes:        'Notificações',
    perfil:              'Perfil',
    terminar_sessao:     'Terminar Sessão',
    /* Saudações */
    bom_dia:             'Bom dia',
    boa_tarde:           'Boa tarde',
    boa_noite:           'Boa noite',
    /* Ações */
    guardar:             'Guardar',
    cancelar:            'Cancelar',
    fechar:              'Fechar',
    ver_detalhes:        'Ver Detalhes',
    candidatar:          'Candidatar-me',
    submeter:            'Submeter Candidatura',
    limpar_filtros:      'Limpar Filtros',
    ver_catalogo:        'Ver Catálogo',
    ver_todos:           'Ver todos',
    nova_candidatura:    'Nova Candidatura',
    continuar_cand:      'Continuar Candidatura',
    ver_pagina_pub:      'Ver Página Pública',
    copiar_link:         'Copiar Link',
    editar_perfil:       'Editar Perfil',
    guardar_alteracoes:  'Guardar Alterações',
    guardar_prefs:       'Guardar Preferências',
    marcar_lidas:        'Marcar todas como lidas',
    /* Dashboard */
    subtitulo_dashboard: 'Dashboard – Progresso na Jornada Técnica',
    resumo_progresso:    'Resumo de Progresso',
    total_obtidos:       'Total de Badges Obtidos',
    badges_processo:     'Badges em Processo',
    total_pontos:        'Total de Pontos',
    proximo_nivel:       'Próximo Nível em Progresso',
    progresso_nivel:     'Progresso por Nível',
    badges_recomendados: 'Badges recomendados para si',
    atividade_recente:   'Atividade Recente',
    marco_alcancado:     'Marco Alcançado',
    sem_atividade:       'Ainda sem atividade',
    sem_atividade_desc:  'Explora o catálogo de badges e submete a tua primeira candidatura.',
    requisitos_cumpridos:'requisitos cumpridos',
    /* Catálogo */
    titulo_catalogo:     'Catálogo de Badges',
    desc_catalogo:       'Explore todos os badges disponíveis, consulte requisitos e candidate-se aos que se adequam ao seu perfil.',
    filtros:             'Filtros',
    pesquisa_nome:       'Pesquisa por Nome',
    pesquisar:           'Pesquisar badges...',
    area:                'Área',
    todas_areas:         'Todas as áreas',
    service_line:        'Service Line',
    todas_sl:            'Todas as service lines',
    nivel:               'Nível',
    todos_niveis:        'Todos os níveis',
    pontos:              'Pontos',
    todos:               'Todos',
    com_pontos:          'Com pontos',
    sem_pontos:          'Sem pontos',
    expiracao:           'Expiração',
    com_expiracao:       'Com expiração',
    sem_expiracao:       'Sem expiração',
    nenhum_badge:        'Nenhum badge encontrado',
    ajustar_filtros:     'Tenta ajustar os filtros de pesquisa.',
    emitido:             'Emitido',
    em_progresso:        'Em Progresso',
    ativo_tag:           'Ativo',
    expirado_tag:        'Expirado',
    conquista_especial:  'Conquista Especial',
    /* Meus Badges */
    titulo_meus:         'Os Meus Badges',
    desc_meus:           'Visualize os badges obtidos, o progresso das certificações e partilhe as suas conquistas profissionais.',
    total_badges:        'Total Badges Obtidos',
    badges_progresso:    'Badges em Progresso',
    badges_expirados:    'Badges Expirados',
    todos_estados:       'Todos os estados',
    estado_ativo:        'Ativo',
    estado_expirado:     'Expirado',
    estado_progresso:    'Em Progresso',
    obtido_em:           'Obtido em',
    expira_em:           'Expira em',
    iniciado_em:         'Iniciado em',
    partilhado:          'Partilhado',
    certificado:         'Certificado',
    sem_badges:          'Ainda não tens badges',
    sem_badges_desc:     'Explora o catálogo e submete a tua primeira candidatura.',
    expira_em_dias:      'Expira em {n} dia',
    expira_em_dias_pl:   'Expira em {n} dias',
    /* Candidaturas */
    titulo_cands:        'Candidaturas a Badges',
    desc_cands:          'Gestão das suas candidaturas',
    info_cands:          'Escolha um badge no catálogo para iniciar uma nova candidatura.',
    badge_col:           'Badge',
    data_submissao:      'Data de Submissão',
    estado_col:          'Estado',
    tempo_sla:           'Tempo Restante (SLA)',
    acao_col:            'Ação',
    editar_cand:         'Editar Candidatura',
    acompanhar:          'Acompanhar Estado',
    ver_resultado:       'Ver Resultado',
    motivo_rejeicao:     'Motivo de Rejeição',
    nenhuma_cand:        'Nenhuma candidatura encontrada',
    procurar_badge:      'Procurar badge...',
    /* Conquistas */
    titulo_conquistas:   'Conquistas',
    desc_conquistas:     'Reconhecimentos especiais obtidos através do progresso no programa de badges.',
    desbloqueadas:       'Conquistas Desbloqueadas',
    em_progresso_s:      'Conquistas em Progresso',
    galeria_publica:     'Galeria Pública',
    sem_conquistas:      'Ainda sem conquistas',
    sem_conquistas_desc: 'Continua a submeter candidaturas para desbloquear conquistas.',
    desbloqueada_em:     'Desbloqueada em',
    perfil_pub_toggle:   'Perfil público de conquistas',
    tornar_visivel:      'Tornar visível para todos',
    url_publica:         'URL Pública',
    ver_pagina_pub_btn:  'Ver Página Pública',
    /* Notificações */
    titulo_notifs:       'Notificações',
    desc_notifs:         'Acompanhe atualizações sobre as suas candidaturas, badges e recomendações.',
    tab_todas:           'Todas',
    tab_candidaturas:    'Candidaturas',
    tab_badges:          'Badges',
    tab_sistema:         'Sistema',
    tab_lembretes:       'Lembretes',
    sem_notifs:          'Sem notificações',
    sem_notifs_desc:     'Ainda não tens notificações nesta categoria.',
    sem_lembretes:       'Sem lembretes',
    sem_lembretes_desc:  'Não tens lembretes ativos de momento.',
    /* Perfil */
    titulo_perfil:       'Perfil',
    desc_perfil:         'Gerencie as suas informações pessoais e preferências da plataforma.',
    info_consultor:      'Informações do Consultor',
    area_label:          'Área:',
    sl_label:            'Service Line:',
    desde_label:         'Consultor desde:',
    perfil_pub_cert:     'Perfil Público de Certificações',
    public_url:          'Public profile URL:',
    estatisticas:        'Estatísticas',
    badges_obtidos_s:    'Badges Obtidos',
    total_pontos_s:      'Total Pontos',
    cands_ativas:        'Candidaturas Ativas',
    conquistas_s:        'Conquistas',
    ver_meus_badges:     'Ver os meus badges →',
    privacidade_rgpd:    'Privacidade e RGPD',
    rgpd_pub:            'Permitir publicação de badges na galeria pública',
    rgpd_linkedin:       'Permitir partilha de badges no LinkedIn',
    rgpd_auto:           'Permitir partilha automática de novas certificações no LinkedIn',
    rgpd_nota:           'Apenas badges aprovados serão visíveis publicamente.',
    rgpd_consentimento:  'Consinto o tratamento dos meus dados pessoais de acordo com o RGPD',
    preferencias:        'Preferências',
    idioma_plataforma:   'Idioma da Plataforma',
    prefs_notif_titulo:  'Preferências de Notificações',
    pref_email_aprov:    'Receber email de aprovação de badges',
    pref_notif_exp:      'Receber notificações de expiração de certificações',
    pref_recomendacoes:  'Receber recomendações de novos badges',
    pref_nota:           'Estas preferências controlam como recebe notificações sobre o progresso das suas certificações.',
    seguranca:           'Segurança',
    alterar_pass:        'Alterar Password',
    alterar_pass_desc:   'Atualize a sua palavra-passe',
    alterar_btn:         'Alterar',
    autenticacao_2fa:    'Autenticação de Dois Fatores',
    conta_protegida:     'A sua conta está protegida com 2FA.',
    adicionar_seg:       'Adicione segurança extra à sua conta.',
    ativar:              'Ativar',
    desativar:           'Desativar',
    /* CandidaturaDetalhe */
    badge_atribuido_info:'Este Badge é atribuído apenas quando todos os requisitos deste nível forem cumpridos.',
    processo_validacao:  'Processo de Validação',
    etapa_submissao:     'Submissão de evidências pelo candidato',
    etapa_revisao:       'Revisão pelo responsável da Service Line',
    etapa_validacao:     'Validação final e atribuição do badge',
    rgpd_detalhe:        'Autorizo a publicação e partilha deste badge na plataforma e em páginas públicas.',
    ver_politica:        'Ver Política RGPD',
    requisitos_badge:    'Requisitos do Badge',
    upload_evidencia:    'Upload de Evidência',
    upload_desc:         'PDF, Imagem, Certificado ou Relatório',
    carregado:           'Carregado',
    pendente:            'Pendente',
    ev_necessarias:      'Evidências Necessárias:',
    feedback_avaliacao:  'Feedback da Avaliação',
    voltar_cands:        'Voltar às candidaturas',
    sucesso_titulo:      'A sua candidatura foi submetida com sucesso!',
    sucesso_email:       'Receberá um email de confirmação em breve.',
    sucesso_processo:    'O processo de validação será iniciado pelo seu Talent Manager.',
    voltar_para_cands:   'Voltar para Candidaturas',
  },

  en: {
    dashboard:           'Dashboard',
    catalogo:            'Badge Catalog',
    meus_badges:         'My Badges',
    candidaturas:        'Applications',
    conquistas:          'Achievements',
    notificacoes:        'Notifications',
    perfil:              'Profile',
    terminar_sessao:     'Sign Out',
    bom_dia:             'Good morning',
    boa_tarde:           'Good afternoon',
    boa_noite:           'Good evening',
    guardar:             'Save',
    cancelar:            'Cancel',
    fechar:              'Close',
    ver_detalhes:        'View Details',
    candidatar:          'Apply',
    submeter:            'Submit Application',
    limpar_filtros:      'Clear Filters',
    ver_catalogo:        'View Catalog',
    ver_todos:           'View all',
    nova_candidatura:    'New Application',
    continuar_cand:      'Continue Application',
    ver_pagina_pub:      'View Public Page',
    copiar_link:         'Copy Link',
    editar_perfil:       'Edit Profile',
    guardar_alteracoes:  'Save Changes',
    guardar_prefs:       'Save Preferences',
    marcar_lidas:        'Mark all as read',
    subtitulo_dashboard: 'Dashboard – Technical Journey Progress',
    resumo_progresso:    'Progress Summary',
    total_obtidos:       'Total Badges Obtained',
    badges_processo:     'Badges In Progress',
    total_pontos:        'Total Points',
    proximo_nivel:       'Next Level Progress',
    progresso_nivel:     'Progress by Level',
    badges_recomendados: 'Recommended badges for you',
    atividade_recente:   'Recent Activity',
    marco_alcancado:     'Milestone Reached',
    sem_atividade:       'No activity yet',
    sem_atividade_desc:  'Explore the badge catalog and submit your first application.',
    requisitos_cumpridos:'requirements completed',
    titulo_catalogo:     'Badge Catalog',
    desc_catalogo:       'Explore all available badges, check requirements and apply for those that suit your profile.',
    filtros:             'Filters',
    pesquisa_nome:       'Search by Name',
    pesquisar:           'Search badges...',
    area:                'Area',
    todas_areas:         'All areas',
    service_line:        'Service Line',
    todas_sl:            'All service lines',
    nivel:               'Level',
    todos_niveis:        'All levels',
    pontos:              'Points',
    todos:               'All',
    com_pontos:          'With points',
    sem_pontos:          'Without points',
    expiracao:           'Expiry',
    com_expiracao:       'With expiry',
    sem_expiracao:       'Without expiry',
    nenhum_badge:        'No badges found',
    ajustar_filtros:     'Try adjusting the search filters.',
    emitido:             'Issued',
    em_progresso:        'In Progress',
    ativo_tag:           'Active',
    expirado_tag:        'Expired',
    conquista_especial:  'Special Achievement',
    titulo_meus:         'My Badges',
    desc_meus:           'View your obtained badges, certification progress and share your professional achievements.',
    total_badges:        'Total Badges Obtained',
    badges_progresso:    'Badges In Progress',
    badges_expirados:    'Expired Badges',
    todos_estados:       'All statuses',
    estado_ativo:        'Active',
    estado_expirado:     'Expired',
    estado_progresso:    'In Progress',
    obtido_em:           'Obtained on',
    expira_em:           'Expires on',
    iniciado_em:         'Started on',
    partilhado:          'Shared',
    certificado:         'Certificate',
    sem_badges:          'No badges yet',
    sem_badges_desc:     'Explore the catalog and submit your first application.',
    expira_em_dias:      'Expires in {n} day',
    expira_em_dias_pl:   'Expires in {n} days',
    titulo_cands:        'Badge Applications',
    desc_cands:          'Manage your applications',
    info_cands:          'Choose a badge from the catalog to start a new application.',
    badge_col:           'Badge',
    data_submissao:      'Submission Date',
    estado_col:          'Status',
    tempo_sla:           'Remaining Time (SLA)',
    acao_col:            'Action',
    editar_cand:         'Edit Application',
    acompanhar:          'Track Status',
    ver_resultado:       'View Result',
    motivo_rejeicao:     'Rejection Reason',
    nenhuma_cand:        'No applications found',
    procurar_badge:      'Search badge...',
    titulo_conquistas:   'Achievements',
    desc_conquistas:     'Special recognitions obtained through progress in the badge program.',
    desbloqueadas:       'Unlocked Achievements',
    em_progresso_s:      'Achievements In Progress',
    galeria_publica:     'Public Gallery',
    sem_conquistas:      'No achievements yet',
    sem_conquistas_desc: 'Keep submitting applications to unlock achievements.',
    desbloqueada_em:     'Unlocked on',
    perfil_pub_toggle:   'Public achievement profile',
    tornar_visivel:      'Make visible to everyone',
    url_publica:         'Public URL',
    ver_pagina_pub_btn:  'View Public Page',
    titulo_notifs:       'Notifications',
    desc_notifs:         'Track updates about your applications, badges and recommendations.',
    tab_todas:           'All',
    tab_candidaturas:    'Applications',
    tab_badges:          'Badges',
    tab_sistema:         'System',
    tab_lembretes:       'Reminders',
    sem_notifs:          'No notifications',
    sem_notifs_desc:     'You have no notifications in this category.',
    sem_lembretes:       'No reminders',
    sem_lembretes_desc:  'You have no active reminders.',
    titulo_perfil:       'Profile',
    desc_perfil:         'Manage your personal information and platform preferences.',
    info_consultor:      'Consultant Information',
    area_label:          'Area:',
    sl_label:            'Service Line:',
    desde_label:         'Consultant since:',
    perfil_pub_cert:     'Public Certification Profile',
    public_url:          'Public profile URL:',
    estatisticas:        'Statistics',
    badges_obtidos_s:    'Badges Obtained',
    total_pontos_s:      'Total Points',
    cands_ativas:        'Active Applications',
    conquistas_s:        'Achievements',
    ver_meus_badges:     'View my badges →',
    privacidade_rgpd:    'Privacy & GDPR',
    rgpd_pub:            'Allow badge publication in the public gallery',
    rgpd_linkedin:       'Allow badge sharing on LinkedIn',
    rgpd_auto:           'Allow automatic sharing of new certifications on LinkedIn',
    rgpd_nota:           'Only approved badges will be publicly visible.',
    rgpd_consentimento:  'I consent to the processing of my personal data in accordance with GDPR',
    preferencias:        'Preferences',
    idioma_plataforma:   'Platform Language',
    prefs_notif_titulo:  'Notification Preferences',
    pref_email_aprov:    'Receive badge approval emails',
    pref_notif_exp:      'Receive certification expiry notifications',
    pref_recomendacoes:  'Receive new badge recommendations',
    pref_nota:           'These preferences control how you receive notifications about your certification progress.',
    seguranca:           'Security',
    alterar_pass:        'Change Password',
    alterar_pass_desc:   'Update your password',
    alterar_btn:         'Change',
    autenticacao_2fa:    'Two-Factor Authentication',
    conta_protegida:     'Your account is protected with 2FA.',
    adicionar_seg:       'Add extra security to your account.',
    ativar:              'Activate',
    desativar:           'Deactivate',
    badge_atribuido_info:'This Badge is only awarded when all requirements for this level are met.',
    processo_validacao:  'Validation Process',
    etapa_submissao:     'Evidence submission by candidate',
    etapa_revisao:       'Review by Service Line manager',
    etapa_validacao:     'Final validation and badge assignment',
    rgpd_detalhe:        'I authorise the publication and sharing of this badge on the platform and public pages.',
    ver_politica:        'View GDPR Policy',
    requisitos_badge:    'Badge Requirements',
    upload_evidencia:    'Upload Evidence',
    upload_desc:         'PDF, Image, Certificate or Report',
    carregado:           'Uploaded',
    pendente:            'Pending',
    ev_necessarias:      'Required Evidence:',
    feedback_avaliacao:  'Evaluation Feedback',
    voltar_cands:        'Back to applications',
    sucesso_titulo:      'Your application was submitted successfully!',
    sucesso_email:       'You will receive a confirmation email shortly.',
    sucesso_processo:    'The validation process will be initiated by your Talent Manager.',
    voltar_para_cands:   'Back to Applications',
  },

  es: {
    dashboard:           'Panel',
    catalogo:            'Catálogo de Insignias',
    meus_badges:         'Mis Insignias',
    candidaturas:        'Solicitudes',
    conquistas:          'Logros',
    notificacoes:        'Notificaciones',
    perfil:              'Perfil',
    terminar_sessao:     'Cerrar Sesión',
    bom_dia:             'Buenos días',
    boa_tarde:           'Buenas tardes',
    boa_noite:           'Buenas noches',
    guardar:             'Guardar',
    cancelar:            'Cancelar',
    fechar:              'Cerrar',
    ver_detalhes:        'Ver Detalles',
    candidatar:          'Postularme',
    submeter:            'Enviar Solicitud',
    limpar_filtros:      'Limpiar Filtros',
    ver_catalogo:        'Ver Catálogo',
    ver_todos:           'Ver todos',
    nova_candidatura:    'Nueva Solicitud',
    continuar_cand:      'Continuar Solicitud',
    ver_pagina_pub:      'Ver Página Pública',
    copiar_link:         'Copiar Enlace',
    editar_perfil:       'Editar Perfil',
    guardar_alteracoes:  'Guardar Cambios',
    guardar_prefs:       'Guardar Preferencias',
    marcar_lidas:        'Marcar todas como leídas',
    subtitulo_dashboard: 'Panel – Progreso en el Viaje Técnico',
    resumo_progresso:    'Resumen de Progreso',
    total_obtidos:       'Total de Insignias Obtenidas',
    badges_processo:     'Insignias en Proceso',
    total_pontos:        'Total de Puntos',
    proximo_nivel:       'Progreso del Siguiente Nivel',
    progresso_nivel:     'Progreso por Nivel',
    badges_recomendados: 'Insignias recomendadas para usted',
    atividade_recente:   'Actividad Reciente',
    marco_alcancado:     'Hito Alcanzado',
    sem_atividade:       'Sin actividad aún',
    sem_atividade_desc:  'Explore el catálogo de insignias y envíe su primera solicitud.',
    requisitos_cumpridos:'requisitos completados',
    titulo_catalogo:     'Catálogo de Insignias',
    desc_catalogo:       'Explore todas las insignias disponibles, consulte requisitos y postúlese a las que se adapten a su perfil.',
    filtros:             'Filtros',
    pesquisa_nome:       'Búsqueda por Nombre',
    pesquisar:           'Buscar insignias...',
    area:                'Área',
    todas_areas:         'Todas las áreas',
    service_line:        'Línea de Servicio',
    todas_sl:            'Todas las líneas de servicio',
    nivel:               'Nivel',
    todos_niveis:        'Todos los niveles',
    pontos:              'Puntos',
    todos:               'Todos',
    com_pontos:          'Con puntos',
    sem_pontos:          'Sin puntos',
    expiracao:           'Vencimiento',
    com_expiracao:       'Con vencimiento',
    sem_expiracao:       'Sin vencimiento',
    nenhum_badge:        'No se encontraron insignias',
    ajustar_filtros:     'Intenta ajustar los filtros de búsqueda.',
    emitido:             'Emitido',
    em_progresso:        'En Progreso',
    ativo_tag:           'Activo',
    expirado_tag:        'Vencido',
    conquista_especial:  'Logro Especial',
    titulo_meus:         'Mis Insignias',
    desc_meus:           'Visualice las insignias obtenidas, el progreso de las certificaciones y comparta sus logros profesionales.',
    total_badges:        'Total Insignias Obtenidas',
    badges_progresso:    'Insignias en Progreso',
    badges_expirados:    'Insignias Vencidas',
    todos_estados:       'Todos los estados',
    estado_ativo:        'Activo',
    estado_expirado:     'Vencido',
    estado_progresso:    'En Progreso',
    obtido_em:           'Obtenida el',
    expira_em:           'Vence el',
    iniciado_em:         'Iniciada el',
    partilhado:          'Compartido',
    certificado:         'Certificado',
    sem_badges:          'Aún no tienes insignias',
    sem_badges_desc:     'Explora el catálogo y envía tu primera solicitud.',
    expira_em_dias:      'Vence en {n} día',
    expira_em_dias_pl:   'Vence en {n} días',
    titulo_cands:        'Solicitudes de Insignias',
    desc_cands:          'Gestión de sus solicitudes',
    info_cands:          'Elija una insignia del catálogo para iniciar una nueva solicitud.',
    badge_col:           'Insignia',
    data_submissao:      'Fecha de Envío',
    estado_col:          'Estado',
    tempo_sla:           'Tiempo Restante (SLA)',
    acao_col:            'Acción',
    editar_cand:         'Editar Solicitud',
    acompanhar:          'Seguir Estado',
    ver_resultado:       'Ver Resultado',
    motivo_rejeicao:     'Motivo de Rechazo',
    nenhuma_cand:        'No se encontraron solicitudes',
    procurar_badge:      'Buscar insignia...',
    titulo_conquistas:   'Logros',
    desc_conquistas:     'Reconocimientos especiales obtenidos a través del progreso en el programa de insignias.',
    desbloqueadas:       'Logros Desbloqueados',
    em_progresso_s:      'Logros en Progreso',
    galeria_publica:     'Galería Pública',
    sem_conquistas:      'Sin logros aún',
    sem_conquistas_desc: 'Sigue enviando solicitudes para desbloquear logros.',
    desbloqueada_em:     'Desbloqueado el',
    perfil_pub_toggle:   'Perfil público de logros',
    tornar_visivel:      'Hacer visible para todos',
    url_publica:         'URL Pública',
    ver_pagina_pub_btn:  'Ver Página Pública',
    titulo_notifs:       'Notificaciones',
    desc_notifs:         'Siga las actualizaciones sobre sus solicitudes, insignias y recomendaciones.',
    tab_todas:           'Todas',
    tab_candidaturas:    'Solicitudes',
    tab_badges:          'Insignias',
    tab_sistema:         'Sistema',
    tab_lembretes:       'Recordatorios',
    sem_notifs:          'Sin notificaciones',
    sem_notifs_desc:     'No tienes notificaciones en esta categoría.',
    sem_lembretes:       'Sin recordatorios',
    sem_lembretes_desc:  'No tienes recordatorios activos.',
    titulo_perfil:       'Perfil',
    desc_perfil:         'Gestione su información personal y preferencias de la plataforma.',
    info_consultor:      'Información del Consultor',
    area_label:          'Área:',
    sl_label:            'Línea de Servicio:',
    desde_label:         'Consultor desde:',
    perfil_pub_cert:     'Perfil Público de Certificaciones',
    public_url:          'URL del perfil público:',
    estatisticas:        'Estadísticas',
    badges_obtidos_s:    'Insignias Obtenidas',
    total_pontos_s:      'Total Puntos',
    cands_ativas:        'Solicitudes Activas',
    conquistas_s:        'Logros',
    ver_meus_badges:     'Ver mis insignias →',
    privacidade_rgpd:    'Privacidad y RGPD',
    rgpd_pub:            'Permitir publicación de insignias en la galería pública',
    rgpd_linkedin:       'Permitir compartir insignias en LinkedIn',
    rgpd_auto:           'Permitir compartir automáticamente nuevas certificaciones en LinkedIn',
    rgpd_nota:           'Solo las insignias aprobadas serán visibles públicamente.',
    rgpd_consentimento:  'Consiento el tratamiento de mis datos personales de acuerdo con el RGPD',
    preferencias:        'Preferencias',
    idioma_plataforma:   'Idioma de la Plataforma',
    prefs_notif_titulo:  'Preferencias de Notificaciones',
    pref_email_aprov:    'Recibir email de aprobación de insignias',
    pref_notif_exp:      'Recibir notificaciones de vencimiento de certificaciones',
    pref_recomendacoes:  'Recibir recomendaciones de nuevas insignias',
    pref_nota:           'Estas preferencias controlan cómo recibe notificaciones sobre el progreso de sus certificaciones.',
    seguranca:           'Seguridad',
    alterar_pass:        'Cambiar Contraseña',
    alterar_pass_desc:   'Actualice su contraseña',
    alterar_btn:         'Cambiar',
    autenticacao_2fa:    'Autenticación de Dos Factores',
    conta_protegida:     'Su cuenta está protegida con 2FA.',
    adicionar_seg:       'Añada seguridad adicional a su cuenta.',
    ativar:              'Activar',
    desativar:           'Desactivar',
    badge_atribuido_info:'Esta Insignia solo se otorga cuando se cumplen todos los requisitos de este nivel.',
    processo_validacao:  'Proceso de Validación',
    etapa_submissao:     'Envío de evidencias por el candidato',
    etapa_revisao:       'Revisión por el responsable de la Línea de Servicio',
    etapa_validacao:     'Validación final y asignación de la insignia',
    rgpd_detalhe:        'Autorizo la publicación y compartición de esta insignia en la plataforma y páginas públicas.',
    ver_politica:        'Ver Política RGPD',
    requisitos_badge:    'Requisitos de la Insignia',
    upload_evidencia:    'Subir Evidencia',
    upload_desc:         'PDF, Imagen, Certificado o Informe',
    carregado:           'Subido',
    pendente:            'Pendiente',
    ev_necessarias:      'Evidencias Requeridas:',
    feedback_avaliacao:  'Comentarios de Evaluación',
    voltar_cands:        'Volver a solicitudes',
    sucesso_titulo:      '¡Su solicitud fue enviada con éxito!',
    sucesso_email:       'Recibirá un email de confirmación en breve.',
    sucesso_processo:    'El proceso de validación será iniciado por su Talent Manager.',
    voltar_para_cands:   'Volver a Solicitudes',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [idioma, setIdioma] = useState(
    () => localStorage.getItem('idioma') || 'pt'
  );

  function mudarIdioma(novoIdioma) {
    setIdioma(novoIdioma);
    localStorage.setItem('idioma', novoIdioma);
  }

  function t(chave) {
    return T[idioma]?.[chave] ?? T.pt[chave] ?? chave;
  }

  return (
    <LanguageContext.Provider value={{ idioma, mudarIdioma, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage tem de ser usado dentro de <LanguageProvider>');
  return ctx;
}
